// Code generated by protoc-gen-go. DO NOT EDIT.
// source: antidote.proto

/*
Package antidoteclient is a generated protocol buffer package.

It is generated from these files:
	antidote.proto

It has these top-level messages:
	ApbErrorResp
	ApbCounterUpdate
	ApbGetCounterResp
	ApbSetUpdate
	ApbGetSetResp
	ApbRegUpdate
	ApbGetRegResp
	ApbGetMVRegResp
	ApbPolicyUpdate
	ApbGetPolicyResp
	ApbIntegerUpdate
	ApbGetIntegerResp
	ApbMapKey
	ApbMapUpdate
	ApbMapNestedUpdate
	ApbGetMapResp
	ApbMapEntry
	ApbCrdtReset
	ApbOperationResp
	ApbTxnProperties
	ApbBoundObject
	ApbReadObjects
	ApbUpdateOp
	ApbUpdateOperation
	ApbUpdateObjects
	ApbStartTransaction
	ApbAbortTransaction
	ApbCommitTransaction
	ApbStaticUpdateObjects
	ApbStaticReadObjects
	ApbStartTransactionResp
	ApbReadObjectResp
	ApbReadObjectsResp
	ApbCommitResp
	ApbStaticReadObjectsResp
*/
package antidoteclient

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CRDTType int32

const (
	CRDTType_COUNTER    CRDTType = 3
	CRDTType_ORSET      CRDTType = 4
	CRDTType_LWWREG     CRDTType = 5
	CRDTType_MVREG      CRDTType = 6
	CRDTType_INTEGER    CRDTType = 7
	CRDTType_GMAP       CRDTType = 8
	CRDTType_AWMAP      CRDTType = 9
	CRDTType_RWSET      CRDTType = 10
	CRDTType_RRMAP      CRDTType = 11
	CRDTType_FATCOUNTER CRDTType = 12
	CRDTType_POLICY     CRDTType = 13
)

var CRDTType_name = map[int32]string{
	3:  "COUNTER",
	4:  "ORSET",
	5:  "LWWREG",
	6:  "MVREG",
	7:  "INTEGER",
	8:  "GMAP",
	9:  "AWMAP",
	10: "RWSET",
	11: "RRMAP",
	12: "FATCOUNTER",
	13: "POLICY",
}
var CRDTType_value = map[string]int32{
	"COUNTER":    3,
	"ORSET":      4,
	"LWWREG":     5,
	"MVREG":      6,
	"INTEGER":    7,
	"GMAP":       8,
	"AWMAP":      9,
	"RWSET":      10,
	"RRMAP":      11,
	"FATCOUNTER": 12,
	"POLICY":     13,
}

func (x CRDTType) Enum() *CRDTType {
	p := new(CRDTType)
	*p = x
	return p
}
func (x CRDTType) String() string {
	return proto.EnumName(CRDTType_name, int32(x))
}
func (x *CRDTType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CRDTType_value, data, "CRDTType")
	if err != nil {
		return err
	}
	*x = CRDTType(value)
	return nil
}
func (CRDTType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ApbSetUpdate_SetOpType int32

const (
	ApbSetUpdate_ADD    ApbSetUpdate_SetOpType = 1
	ApbSetUpdate_REMOVE ApbSetUpdate_SetOpType = 2
)

var ApbSetUpdate_SetOpType_name = map[int32]string{
	1: "ADD",
	2: "REMOVE",
}
var ApbSetUpdate_SetOpType_value = map[string]int32{
	"ADD":    1,
	"REMOVE": 2,
}

func (x ApbSetUpdate_SetOpType) Enum() *ApbSetUpdate_SetOpType {
	p := new(ApbSetUpdate_SetOpType)
	*p = x
	return p
}
func (x ApbSetUpdate_SetOpType) String() string {
	return proto.EnumName(ApbSetUpdate_SetOpType_name, int32(x))
}
func (x *ApbSetUpdate_SetOpType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ApbSetUpdate_SetOpType_value, data, "ApbSetUpdate_SetOpType")
	if err != nil {
		return err
	}
	*x = ApbSetUpdate_SetOpType(value)
	return nil
}
func (ApbSetUpdate_SetOpType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

// ------------------
// Error messages
type ApbErrorResp struct {
	Errmsg           []byte  `protobuf:"bytes,1,req,name=errmsg" json:"errmsg,omitempty"`
	Errcode          *uint32 `protobuf:"varint,2,req,name=errcode" json:"errcode,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApbErrorResp) Reset()                    { *m = ApbErrorResp{} }
func (m *ApbErrorResp) String() string            { return proto.CompactTextString(m) }
func (*ApbErrorResp) ProtoMessage()               {}
func (*ApbErrorResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ApbErrorResp) GetErrmsg() []byte {
	if m != nil {
		return m.Errmsg
	}
	return nil
}

func (m *ApbErrorResp) GetErrcode() uint32 {
	if m != nil && m.Errcode != nil {
		return *m.Errcode
	}
	return 0
}

// Counter increment requenst
type ApbCounterUpdate struct {
	// inc indicates the value to be incremented. To decrement, use a negative value. If no value is given, it will be considered as an increment by 1
	Inc              *int64 `protobuf:"zigzag64,1,opt,name=inc" json:"inc,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ApbCounterUpdate) Reset()                    { *m = ApbCounterUpdate{} }
func (m *ApbCounterUpdate) String() string            { return proto.CompactTextString(m) }
func (*ApbCounterUpdate) ProtoMessage()               {}
func (*ApbCounterUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ApbCounterUpdate) GetInc() int64 {
	if m != nil && m.Inc != nil {
		return *m.Inc
	}
	return 0
}

// Response operation
type ApbGetCounterResp struct {
	Value            *int32 `protobuf:"zigzag32,1,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ApbGetCounterResp) Reset()                    { *m = ApbGetCounterResp{} }
func (m *ApbGetCounterResp) String() string            { return proto.CompactTextString(m) }
func (*ApbGetCounterResp) ProtoMessage()               {}
func (*ApbGetCounterResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ApbGetCounterResp) GetValue() int32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

// Set updates request
type ApbSetUpdate struct {
	Optype           *ApbSetUpdate_SetOpType `protobuf:"varint,1,req,name=optype,enum=ApbSetUpdate_SetOpType" json:"optype,omitempty"`
	Adds             [][]byte                `protobuf:"bytes,2,rep,name=adds" json:"adds,omitempty"`
	Rems             [][]byte                `protobuf:"bytes,3,rep,name=rems" json:"rems,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *ApbSetUpdate) Reset()                    { *m = ApbSetUpdate{} }
func (m *ApbSetUpdate) String() string            { return proto.CompactTextString(m) }
func (*ApbSetUpdate) ProtoMessage()               {}
func (*ApbSetUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ApbSetUpdate) GetOptype() ApbSetUpdate_SetOpType {
	if m != nil && m.Optype != nil {
		return *m.Optype
	}
	return ApbSetUpdate_ADD
}

func (m *ApbSetUpdate) GetAdds() [][]byte {
	if m != nil {
		return m.Adds
	}
	return nil
}

func (m *ApbSetUpdate) GetRems() [][]byte {
	if m != nil {
		return m.Rems
	}
	return nil
}

// Get set request
type ApbGetSetResp struct {
	Value            [][]byte `protobuf:"bytes,1,rep,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ApbGetSetResp) Reset()                    { *m = ApbGetSetResp{} }
func (m *ApbGetSetResp) String() string            { return proto.CompactTextString(m) }
func (*ApbGetSetResp) ProtoMessage()               {}
func (*ApbGetSetResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ApbGetSetResp) GetValue() [][]byte {
	if m != nil {
		return m.Value
	}
	return nil
}

// Register update
type ApbRegUpdate struct {
	Value            []byte `protobuf:"bytes,1,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ApbRegUpdate) Reset()                    { *m = ApbRegUpdate{} }
func (m *ApbRegUpdate) String() string            { return proto.CompactTextString(m) }
func (*ApbRegUpdate) ProtoMessage()               {}
func (*ApbRegUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ApbRegUpdate) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

// Response operation
type ApbGetRegResp struct {
	Value            []byte `protobuf:"bytes,1,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ApbGetRegResp) Reset()                    { *m = ApbGetRegResp{} }
func (m *ApbGetRegResp) String() string            { return proto.CompactTextString(m) }
func (*ApbGetRegResp) ProtoMessage()               {}
func (*ApbGetRegResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ApbGetRegResp) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

// response:
type ApbGetMVRegResp struct {
	Values           [][]byte `protobuf:"bytes,1,rep,name=values" json:"values,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ApbGetMVRegResp) Reset()                    { *m = ApbGetMVRegResp{} }
func (m *ApbGetMVRegResp) String() string            { return proto.CompactTextString(m) }
func (*ApbGetMVRegResp) ProtoMessage()               {}
func (*ApbGetMVRegResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ApbGetMVRegResp) GetValues() [][]byte {
	if m != nil {
		return m.Values
	}
	return nil
}

type ApbPolicyUpdate struct {
	Permissions      [][]byte `protobuf:"bytes,1,rep,name=permissions" json:"permissions,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ApbPolicyUpdate) Reset()                    { *m = ApbPolicyUpdate{} }
func (m *ApbPolicyUpdate) String() string            { return proto.CompactTextString(m) }
func (*ApbPolicyUpdate) ProtoMessage()               {}
func (*ApbPolicyUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ApbPolicyUpdate) GetPermissions() [][]byte {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type ApbGetPolicyResp struct {
	Permissions      [][]byte `protobuf:"bytes,1,rep,name=permissions" json:"permissions,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ApbGetPolicyResp) Reset()                    { *m = ApbGetPolicyResp{} }
func (m *ApbGetPolicyResp) String() string            { return proto.CompactTextString(m) }
func (*ApbGetPolicyResp) ProtoMessage()               {}
func (*ApbGetPolicyResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ApbGetPolicyResp) GetPermissions() [][]byte {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type ApbIntegerUpdate struct {
	// choose one of the following:
	// increment the integer
	Inc *int64 `protobuf:"zigzag64,1,opt,name=inc" json:"inc,omitempty"`
	// set the integer to a number
	Set              *int64 `protobuf:"zigzag64,2,opt,name=set" json:"set,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ApbIntegerUpdate) Reset()                    { *m = ApbIntegerUpdate{} }
func (m *ApbIntegerUpdate) String() string            { return proto.CompactTextString(m) }
func (*ApbIntegerUpdate) ProtoMessage()               {}
func (*ApbIntegerUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ApbIntegerUpdate) GetInc() int64 {
	if m != nil && m.Inc != nil {
		return *m.Inc
	}
	return 0
}

func (m *ApbIntegerUpdate) GetSet() int64 {
	if m != nil && m.Set != nil {
		return *m.Set
	}
	return 0
}

type ApbGetIntegerResp struct {
	Value            *int64 `protobuf:"zigzag64,1,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ApbGetIntegerResp) Reset()                    { *m = ApbGetIntegerResp{} }
func (m *ApbGetIntegerResp) String() string            { return proto.CompactTextString(m) }
func (*ApbGetIntegerResp) ProtoMessage()               {}
func (*ApbGetIntegerResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ApbGetIntegerResp) GetValue() int64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

type ApbMapKey struct {
	Key              []byte    `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Type             *CRDTType `protobuf:"varint,2,req,name=type,enum=CRDTType" json:"type,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *ApbMapKey) Reset()                    { *m = ApbMapKey{} }
func (m *ApbMapKey) String() string            { return proto.CompactTextString(m) }
func (*ApbMapKey) ProtoMessage()               {}
func (*ApbMapKey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ApbMapKey) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ApbMapKey) GetType() CRDTType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return CRDTType_COUNTER
}

type ApbMapUpdate struct {
	Updates          []*ApbMapNestedUpdate `protobuf:"bytes,1,rep,name=updates" json:"updates,omitempty"`
	RemovedKeys      []*ApbMapKey          `protobuf:"bytes,2,rep,name=removedKeys" json:"removedKeys,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *ApbMapUpdate) Reset()                    { *m = ApbMapUpdate{} }
func (m *ApbMapUpdate) String() string            { return proto.CompactTextString(m) }
func (*ApbMapUpdate) ProtoMessage()               {}
func (*ApbMapUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *ApbMapUpdate) GetUpdates() []*ApbMapNestedUpdate {
	if m != nil {
		return m.Updates
	}
	return nil
}

func (m *ApbMapUpdate) GetRemovedKeys() []*ApbMapKey {
	if m != nil {
		return m.RemovedKeys
	}
	return nil
}

type ApbMapNestedUpdate struct {
	Key              *ApbMapKey          `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Update           *ApbUpdateOperation `protobuf:"bytes,2,req,name=update" json:"update,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ApbMapNestedUpdate) Reset()                    { *m = ApbMapNestedUpdate{} }
func (m *ApbMapNestedUpdate) String() string            { return proto.CompactTextString(m) }
func (*ApbMapNestedUpdate) ProtoMessage()               {}
func (*ApbMapNestedUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *ApbMapNestedUpdate) GetKey() *ApbMapKey {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ApbMapNestedUpdate) GetUpdate() *ApbUpdateOperation {
	if m != nil {
		return m.Update
	}
	return nil
}

type ApbGetMapResp struct {
	Entries          []*ApbMapEntry `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *ApbGetMapResp) Reset()                    { *m = ApbGetMapResp{} }
func (m *ApbGetMapResp) String() string            { return proto.CompactTextString(m) }
func (*ApbGetMapResp) ProtoMessage()               {}
func (*ApbGetMapResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *ApbGetMapResp) GetEntries() []*ApbMapEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type ApbMapEntry struct {
	Key              *ApbMapKey         `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value            *ApbReadObjectResp `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *ApbMapEntry) Reset()                    { *m = ApbMapEntry{} }
func (m *ApbMapEntry) String() string            { return proto.CompactTextString(m) }
func (*ApbMapEntry) ProtoMessage()               {}
func (*ApbMapEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *ApbMapEntry) GetKey() *ApbMapKey {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ApbMapEntry) GetValue() *ApbReadObjectResp {
	if m != nil {
		return m.Value
	}
	return nil
}

// General reset operation
type ApbCrdtReset struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ApbCrdtReset) Reset()                    { *m = ApbCrdtReset{} }
func (m *ApbCrdtReset) String() string            { return proto.CompactTextString(m) }
func (*ApbCrdtReset) ProtoMessage()               {}
func (*ApbCrdtReset) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

// Response operation
type ApbOperationResp struct {
	Success          *bool   `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	Errorcode        *uint32 `protobuf:"varint,2,opt,name=errorcode" json:"errorcode,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApbOperationResp) Reset()                    { *m = ApbOperationResp{} }
func (m *ApbOperationResp) String() string            { return proto.CompactTextString(m) }
func (*ApbOperationResp) ProtoMessage()               {}
func (*ApbOperationResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *ApbOperationResp) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

func (m *ApbOperationResp) GetErrorcode() uint32 {
	if m != nil && m.Errorcode != nil {
		return *m.Errorcode
	}
	return 0
}

// Properties parameters of a transaction
type ApbTxnProperties struct {
	ReadWrite        *uint32 `protobuf:"varint,1,opt,name=read_write,json=readWrite" json:"read_write,omitempty"`
	RedBlue          *uint32 `protobuf:"varint,2,opt,name=red_blue,json=redBlue" json:"red_blue,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApbTxnProperties) Reset()                    { *m = ApbTxnProperties{} }
func (m *ApbTxnProperties) String() string            { return proto.CompactTextString(m) }
func (*ApbTxnProperties) ProtoMessage()               {}
func (*ApbTxnProperties) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *ApbTxnProperties) GetReadWrite() uint32 {
	if m != nil && m.ReadWrite != nil {
		return *m.ReadWrite
	}
	return 0
}

func (m *ApbTxnProperties) GetRedBlue() uint32 {
	if m != nil && m.RedBlue != nil {
		return *m.RedBlue
	}
	return 0
}

// Object (Key) representation
type ApbBoundObject struct {
	Key              []byte    `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Type             *CRDTType `protobuf:"varint,2,req,name=type,enum=CRDTType" json:"type,omitempty"`
	Bucket           []byte    `protobuf:"bytes,3,req,name=bucket" json:"bucket,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *ApbBoundObject) Reset()                    { *m = ApbBoundObject{} }
func (m *ApbBoundObject) String() string            { return proto.CompactTextString(m) }
func (*ApbBoundObject) ProtoMessage()               {}
func (*ApbBoundObject) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *ApbBoundObject) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ApbBoundObject) GetType() CRDTType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return CRDTType_COUNTER
}

func (m *ApbBoundObject) GetBucket() []byte {
	if m != nil {
		return m.Bucket
	}
	return nil
}

// Objects to be read
type ApbReadObjects struct {
	Boundobjects          []*ApbBoundObject `protobuf:"bytes,1,rep,name=boundobjects" json:"boundobjects,omitempty"`
	TransactionDescriptor []byte            `protobuf:"bytes,2,req,name=transaction_descriptor,json=transactionDescriptor" json:"transaction_descriptor,omitempty"`
	XXX_unrecognized      []byte            `json:"-"`
}

func (m *ApbReadObjects) Reset()                    { *m = ApbReadObjects{} }
func (m *ApbReadObjects) String() string            { return proto.CompactTextString(m) }
func (*ApbReadObjects) ProtoMessage()               {}
func (*ApbReadObjects) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *ApbReadObjects) GetBoundobjects() []*ApbBoundObject {
	if m != nil {
		return m.Boundobjects
	}
	return nil
}

func (m *ApbReadObjects) GetTransactionDescriptor() []byte {
	if m != nil {
		return m.TransactionDescriptor
	}
	return nil
}

// An Object to be updated with specified operation
type ApbUpdateOp struct {
	Boundobject      *ApbBoundObject     `protobuf:"bytes,1,req,name=boundobject" json:"boundobject,omitempty"`
	Operation        *ApbUpdateOperation `protobuf:"bytes,2,req,name=operation" json:"operation,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ApbUpdateOp) Reset()                    { *m = ApbUpdateOp{} }
func (m *ApbUpdateOp) String() string            { return proto.CompactTextString(m) }
func (*ApbUpdateOp) ProtoMessage()               {}
func (*ApbUpdateOp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *ApbUpdateOp) GetBoundobject() *ApbBoundObject {
	if m != nil {
		return m.Boundobject
	}
	return nil
}

func (m *ApbUpdateOp) GetOperation() *ApbUpdateOperation {
	if m != nil {
		return m.Operation
	}
	return nil
}

type ApbUpdateOperation struct {
	Counterop        *ApbCounterUpdate `protobuf:"bytes,1,opt,name=counterop" json:"counterop,omitempty"`
	Setop            *ApbSetUpdate     `protobuf:"bytes,2,opt,name=setop" json:"setop,omitempty"`
	Regop            *ApbRegUpdate     `protobuf:"bytes,3,opt,name=regop" json:"regop,omitempty"`
	Integerop        *ApbIntegerUpdate `protobuf:"bytes,4,opt,name=integerop" json:"integerop,omitempty"`
	Mapop            *ApbMapUpdate     `protobuf:"bytes,5,opt,name=mapop" json:"mapop,omitempty"`
	Resetop          *ApbCrdtReset     `protobuf:"bytes,6,opt,name=resetop" json:"resetop,omitempty"`
	Policyop         *ApbPolicyUpdate  `protobuf:"bytes,7,opt,name=policyop" json:"policyop,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *ApbUpdateOperation) Reset()                    { *m = ApbUpdateOperation{} }
func (m *ApbUpdateOperation) String() string            { return proto.CompactTextString(m) }
func (*ApbUpdateOperation) ProtoMessage()               {}
func (*ApbUpdateOperation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *ApbUpdateOperation) GetCounterop() *ApbCounterUpdate {
	if m != nil {
		return m.Counterop
	}
	return nil
}

func (m *ApbUpdateOperation) GetSetop() *ApbSetUpdate {
	if m != nil {
		return m.Setop
	}
	return nil
}

func (m *ApbUpdateOperation) GetRegop() *ApbRegUpdate {
	if m != nil {
		return m.Regop
	}
	return nil
}

func (m *ApbUpdateOperation) GetIntegerop() *ApbIntegerUpdate {
	if m != nil {
		return m.Integerop
	}
	return nil
}

func (m *ApbUpdateOperation) GetMapop() *ApbMapUpdate {
	if m != nil {
		return m.Mapop
	}
	return nil
}

func (m *ApbUpdateOperation) GetResetop() *ApbCrdtReset {
	if m != nil {
		return m.Resetop
	}
	return nil
}

func (m *ApbUpdateOperation) GetPolicyop() *ApbPolicyUpdate {
	if m != nil {
		return m.Policyop
	}
	return nil
}

// Objects to be updated
type ApbUpdateObjects struct {
	Updates               []*ApbUpdateOp `protobuf:"bytes,1,rep,name=updates" json:"updates,omitempty"`
	TransactionDescriptor []byte         `protobuf:"bytes,2,req,name=transaction_descriptor,json=transactionDescriptor" json:"transaction_descriptor,omitempty"`
	XXX_unrecognized      []byte         `json:"-"`
}

func (m *ApbUpdateObjects) Reset()                    { *m = ApbUpdateObjects{} }
func (m *ApbUpdateObjects) String() string            { return proto.CompactTextString(m) }
func (*ApbUpdateObjects) ProtoMessage()               {}
func (*ApbUpdateObjects) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *ApbUpdateObjects) GetUpdates() []*ApbUpdateOp {
	if m != nil {
		return m.Updates
	}
	return nil
}

func (m *ApbUpdateObjects) GetTransactionDescriptor() []byte {
	if m != nil {
		return m.TransactionDescriptor
	}
	return nil
}

// Start Transaction
type ApbStartTransaction struct {
	Timestamp        []byte            `protobuf:"bytes,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Properties       *ApbTxnProperties `protobuf:"bytes,2,opt,name=properties" json:"properties,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *ApbStartTransaction) Reset()                    { *m = ApbStartTransaction{} }
func (m *ApbStartTransaction) String() string            { return proto.CompactTextString(m) }
func (*ApbStartTransaction) ProtoMessage()               {}
func (*ApbStartTransaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *ApbStartTransaction) GetTimestamp() []byte {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *ApbStartTransaction) GetProperties() *ApbTxnProperties {
	if m != nil {
		return m.Properties
	}
	return nil
}

// Abort Transaction
type ApbAbortTransaction struct {
	TransactionDescriptor []byte `protobuf:"bytes,1,req,name=transaction_descriptor,json=transactionDescriptor" json:"transaction_descriptor,omitempty"`
	XXX_unrecognized      []byte `json:"-"`
}

func (m *ApbAbortTransaction) Reset()                    { *m = ApbAbortTransaction{} }
func (m *ApbAbortTransaction) String() string            { return proto.CompactTextString(m) }
func (*ApbAbortTransaction) ProtoMessage()               {}
func (*ApbAbortTransaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *ApbAbortTransaction) GetTransactionDescriptor() []byte {
	if m != nil {
		return m.TransactionDescriptor
	}
	return nil
}

// Commit Transaction
type ApbCommitTransaction struct {
	TransactionDescriptor []byte `protobuf:"bytes,1,req,name=transaction_descriptor,json=transactionDescriptor" json:"transaction_descriptor,omitempty"`
	XXX_unrecognized      []byte `json:"-"`
}

func (m *ApbCommitTransaction) Reset()                    { *m = ApbCommitTransaction{} }
func (m *ApbCommitTransaction) String() string            { return proto.CompactTextString(m) }
func (*ApbCommitTransaction) ProtoMessage()               {}
func (*ApbCommitTransaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *ApbCommitTransaction) GetTransactionDescriptor() []byte {
	if m != nil {
		return m.TransactionDescriptor
	}
	return nil
}

type ApbStaticUpdateObjects struct {
	Transaction      *ApbStartTransaction `protobuf:"bytes,1,req,name=transaction" json:"transaction,omitempty"`
	Updates          []*ApbUpdateOp       `protobuf:"bytes,2,rep,name=updates" json:"updates,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *ApbStaticUpdateObjects) Reset()                    { *m = ApbStaticUpdateObjects{} }
func (m *ApbStaticUpdateObjects) String() string            { return proto.CompactTextString(m) }
func (*ApbStaticUpdateObjects) ProtoMessage()               {}
func (*ApbStaticUpdateObjects) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *ApbStaticUpdateObjects) GetTransaction() *ApbStartTransaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *ApbStaticUpdateObjects) GetUpdates() []*ApbUpdateOp {
	if m != nil {
		return m.Updates
	}
	return nil
}

type ApbStaticReadObjects struct {
	Transaction      *ApbStartTransaction `protobuf:"bytes,1,req,name=transaction" json:"transaction,omitempty"`
	Objects          []*ApbBoundObject    `protobuf:"bytes,2,rep,name=objects" json:"objects,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *ApbStaticReadObjects) Reset()                    { *m = ApbStaticReadObjects{} }
func (m *ApbStaticReadObjects) String() string            { return proto.CompactTextString(m) }
func (*ApbStaticReadObjects) ProtoMessage()               {}
func (*ApbStaticReadObjects) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *ApbStaticReadObjects) GetTransaction() *ApbStartTransaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *ApbStaticReadObjects) GetObjects() []*ApbBoundObject {
	if m != nil {
		return m.Objects
	}
	return nil
}

// Start transaction response
type ApbStartTransactionResp struct {
	Success               *bool   `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	TransactionDescriptor []byte  `protobuf:"bytes,2,opt,name=transaction_descriptor,json=transactionDescriptor" json:"transaction_descriptor,omitempty"`
	Errorcode             *uint32 `protobuf:"varint,3,opt,name=errorcode" json:"errorcode,omitempty"`
	XXX_unrecognized      []byte  `json:"-"`
}

func (m *ApbStartTransactionResp) Reset()                    { *m = ApbStartTransactionResp{} }
func (m *ApbStartTransactionResp) String() string            { return proto.CompactTextString(m) }
func (*ApbStartTransactionResp) ProtoMessage()               {}
func (*ApbStartTransactionResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *ApbStartTransactionResp) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

func (m *ApbStartTransactionResp) GetTransactionDescriptor() []byte {
	if m != nil {
		return m.TransactionDescriptor
	}
	return nil
}

func (m *ApbStartTransactionResp) GetErrorcode() uint32 {
	if m != nil && m.Errorcode != nil {
		return *m.Errorcode
	}
	return 0
}

// Read Objects Response
type ApbReadObjectResp struct {
	// one of the following:
	Counter          *ApbGetCounterResp `protobuf:"bytes,1,opt,name=counter" json:"counter,omitempty"`
	Set              *ApbGetSetResp     `protobuf:"bytes,2,opt,name=set" json:"set,omitempty"`
	Reg              *ApbGetRegResp     `protobuf:"bytes,3,opt,name=reg" json:"reg,omitempty"`
	Mvreg            *ApbGetMVRegResp   `protobuf:"bytes,4,opt,name=mvreg" json:"mvreg,omitempty"`
	Int              *ApbGetIntegerResp `protobuf:"bytes,5,opt,name=int" json:"int,omitempty"`
	Map              *ApbGetMapResp     `protobuf:"bytes,6,opt,name=map" json:"map,omitempty"`
	Policy           *ApbGetPolicyResp  `protobuf:"bytes,7,opt,name=policy" json:"policy,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *ApbReadObjectResp) Reset()                    { *m = ApbReadObjectResp{} }
func (m *ApbReadObjectResp) String() string            { return proto.CompactTextString(m) }
func (*ApbReadObjectResp) ProtoMessage()               {}
func (*ApbReadObjectResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *ApbReadObjectResp) GetCounter() *ApbGetCounterResp {
	if m != nil {
		return m.Counter
	}
	return nil
}

func (m *ApbReadObjectResp) GetSet() *ApbGetSetResp {
	if m != nil {
		return m.Set
	}
	return nil
}

func (m *ApbReadObjectResp) GetReg() *ApbGetRegResp {
	if m != nil {
		return m.Reg
	}
	return nil
}

func (m *ApbReadObjectResp) GetMvreg() *ApbGetMVRegResp {
	if m != nil {
		return m.Mvreg
	}
	return nil
}

func (m *ApbReadObjectResp) GetInt() *ApbGetIntegerResp {
	if m != nil {
		return m.Int
	}
	return nil
}

func (m *ApbReadObjectResp) GetMap() *ApbGetMapResp {
	if m != nil {
		return m.Map
	}
	return nil
}

func (m *ApbReadObjectResp) GetPolicy() *ApbGetPolicyResp {
	if m != nil {
		return m.Policy
	}
	return nil
}

type ApbReadObjectsResp struct {
	Success          *bool                `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	Objects          []*ApbReadObjectResp `protobuf:"bytes,2,rep,name=objects" json:"objects,omitempty"`
	Errorcode        *uint32              `protobuf:"varint,3,opt,name=errorcode" json:"errorcode,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *ApbReadObjectsResp) Reset()                    { *m = ApbReadObjectsResp{} }
func (m *ApbReadObjectsResp) String() string            { return proto.CompactTextString(m) }
func (*ApbReadObjectsResp) ProtoMessage()               {}
func (*ApbReadObjectsResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *ApbReadObjectsResp) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

func (m *ApbReadObjectsResp) GetObjects() []*ApbReadObjectResp {
	if m != nil {
		return m.Objects
	}
	return nil
}

func (m *ApbReadObjectsResp) GetErrorcode() uint32 {
	if m != nil && m.Errorcode != nil {
		return *m.Errorcode
	}
	return 0
}

// Commit Response
type ApbCommitResp struct {
	Success          *bool   `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	CommitTime       []byte  `protobuf:"bytes,2,opt,name=commit_time,json=commitTime" json:"commit_time,omitempty"`
	Errorcode        *uint32 `protobuf:"varint,3,opt,name=errorcode" json:"errorcode,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApbCommitResp) Reset()                    { *m = ApbCommitResp{} }
func (m *ApbCommitResp) String() string            { return proto.CompactTextString(m) }
func (*ApbCommitResp) ProtoMessage()               {}
func (*ApbCommitResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *ApbCommitResp) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

func (m *ApbCommitResp) GetCommitTime() []byte {
	if m != nil {
		return m.CommitTime
	}
	return nil
}

func (m *ApbCommitResp) GetErrorcode() uint32 {
	if m != nil && m.Errorcode != nil {
		return *m.Errorcode
	}
	return 0
}

type ApbStaticReadObjectsResp struct {
	Objects          *ApbReadObjectsResp `protobuf:"bytes,1,req,name=objects" json:"objects,omitempty"`
	Committime       *ApbCommitResp      `protobuf:"bytes,2,req,name=committime" json:"committime,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ApbStaticReadObjectsResp) Reset()                    { *m = ApbStaticReadObjectsResp{} }
func (m *ApbStaticReadObjectsResp) String() string            { return proto.CompactTextString(m) }
func (*ApbStaticReadObjectsResp) ProtoMessage()               {}
func (*ApbStaticReadObjectsResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *ApbStaticReadObjectsResp) GetObjects() *ApbReadObjectsResp {
	if m != nil {
		return m.Objects
	}
	return nil
}

func (m *ApbStaticReadObjectsResp) GetCommittime() *ApbCommitResp {
	if m != nil {
		return m.Committime
	}
	return nil
}

func init() {
	proto.RegisterType((*ApbErrorResp)(nil), "ApbErrorResp")
	proto.RegisterType((*ApbCounterUpdate)(nil), "ApbCounterUpdate")
	proto.RegisterType((*ApbGetCounterResp)(nil), "ApbGetCounterResp")
	proto.RegisterType((*ApbSetUpdate)(nil), "ApbSetUpdate")
	proto.RegisterType((*ApbGetSetResp)(nil), "ApbGetSetResp")
	proto.RegisterType((*ApbRegUpdate)(nil), "ApbRegUpdate")
	proto.RegisterType((*ApbGetRegResp)(nil), "ApbGetRegResp")
	proto.RegisterType((*ApbGetMVRegResp)(nil), "ApbGetMVRegResp")
	proto.RegisterType((*ApbPolicyUpdate)(nil), "ApbPolicyUpdate")
	proto.RegisterType((*ApbGetPolicyResp)(nil), "ApbGetPolicyResp")
	proto.RegisterType((*ApbIntegerUpdate)(nil), "ApbIntegerUpdate")
	proto.RegisterType((*ApbGetIntegerResp)(nil), "ApbGetIntegerResp")
	proto.RegisterType((*ApbMapKey)(nil), "ApbMapKey")
	proto.RegisterType((*ApbMapUpdate)(nil), "ApbMapUpdate")
	proto.RegisterType((*ApbMapNestedUpdate)(nil), "ApbMapNestedUpdate")
	proto.RegisterType((*ApbGetMapResp)(nil), "ApbGetMapResp")
	proto.RegisterType((*ApbMapEntry)(nil), "ApbMapEntry")
	proto.RegisterType((*ApbCrdtReset)(nil), "ApbCrdtReset")
	proto.RegisterType((*ApbOperationResp)(nil), "ApbOperationResp")
	proto.RegisterType((*ApbTxnProperties)(nil), "ApbTxnProperties")
	proto.RegisterType((*ApbBoundObject)(nil), "ApbBoundObject")
	proto.RegisterType((*ApbReadObjects)(nil), "ApbReadObjects")
	proto.RegisterType((*ApbUpdateOp)(nil), "ApbUpdateOp")
	proto.RegisterType((*ApbUpdateOperation)(nil), "ApbUpdateOperation")
	proto.RegisterType((*ApbUpdateObjects)(nil), "ApbUpdateObjects")
	proto.RegisterType((*ApbStartTransaction)(nil), "ApbStartTransaction")
	proto.RegisterType((*ApbAbortTransaction)(nil), "ApbAbortTransaction")
	proto.RegisterType((*ApbCommitTransaction)(nil), "ApbCommitTransaction")
	proto.RegisterType((*ApbStaticUpdateObjects)(nil), "ApbStaticUpdateObjects")
	proto.RegisterType((*ApbStaticReadObjects)(nil), "ApbStaticReadObjects")
	proto.RegisterType((*ApbStartTransactionResp)(nil), "ApbStartTransactionResp")
	proto.RegisterType((*ApbReadObjectResp)(nil), "ApbReadObjectResp")
	proto.RegisterType((*ApbReadObjectsResp)(nil), "ApbReadObjectsResp")
	proto.RegisterType((*ApbCommitResp)(nil), "ApbCommitResp")
	proto.RegisterType((*ApbStaticReadObjectsResp)(nil), "ApbStaticReadObjectsResp")
	proto.RegisterEnum("CRDTType", CRDTType_name, CRDTType_value)
	proto.RegisterEnum("ApbSetUpdate_SetOpType", ApbSetUpdate_SetOpType_name, ApbSetUpdate_SetOpType_value)
}

func init() { proto.RegisterFile("antidote.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x6d, 0x6f, 0x1b, 0xc5,
	0x13, 0x97, 0xed, 0xc4, 0x8e, 0xe7, 0x9c, 0xd4, 0xd9, 0xf6, 0x9f, 0xde, 0x5f, 0x2a, 0x60, 0x1d,
	0xa5, 0x24, 0x90, 0x5e, 0xd5, 0x14, 0xca, 0x2b, 0x24, 0x9c, 0xc4, 0x44, 0xa5, 0x71, 0x1d, 0x6d,
	0xdc, 0x46, 0xf4, 0x4d, 0x74, 0xbe, 0x1b, 0xc2, 0xd1, 0xfa, 0x6e, 0xd9, 0x5b, 0x97, 0x1a, 0xf1,
	0x01, 0xe0, 0x0d, 0x9f, 0x81, 0x0f, 0xc2, 0x87, 0x43, 0xfb, 0x74, 0x0f, 0x4e, 0x1a, 0x8b, 0x8a,
	0x77, 0x7b, 0x33, 0xbf, 0x9d, 0x87, 0x9d, 0xd9, 0xdf, 0xce, 0xc1, 0x46, 0x90, 0x88, 0x38, 0x4a,
	0x05, 0xfa, 0x8c, 0xa7, 0x22, 0xf5, 0xbe, 0x81, 0x4e, 0x9f, 0x4d, 0x06, 0x9c, 0xa7, 0x9c, 0x62,
	0xc6, 0xc8, 0x16, 0x34, 0x91, 0xf3, 0x69, 0x76, 0xe1, 0xd6, 0x7a, 0xf5, 0xed, 0x0e, 0x35, 0x5f,
	0xc4, 0x85, 0x16, 0x72, 0x1e, 0xa6, 0x11, 0xba, 0xf5, 0x5e, 0x7d, 0x7b, 0x9d, 0xda, 0x4f, 0xef,
	0x2e, 0x74, 0xfb, 0x6c, 0x72, 0x90, 0xce, 0x12, 0x81, 0xfc, 0x39, 0x8b, 0x02, 0x81, 0xa4, 0x0b,
	0x8d, 0x38, 0x09, 0xdd, 0x5a, 0xaf, 0xb6, 0x4d, 0xa8, 0x5c, 0x7a, 0x3b, 0xb0, 0xd9, 0x67, 0x93,
	0x23, 0x14, 0x06, 0xa8, 0x9c, 0xdd, 0x82, 0xd5, 0x37, 0xc1, 0xeb, 0x19, 0x2a, 0x5f, 0x9b, 0x54,
	0x7f, 0x78, 0x7f, 0xd4, 0x54, 0x4c, 0xa7, 0x28, 0x8c, 0xb5, 0x07, 0xd0, 0x4c, 0x99, 0x98, 0x33,
	0x8d, 0xdb, 0xd8, 0xbb, 0xed, 0x97, 0xd5, 0xfe, 0x29, 0x8a, 0x11, 0x1b, 0xcf, 0x19, 0x52, 0x03,
	0x23, 0x04, 0x56, 0x82, 0x28, 0xca, 0xdc, 0x7a, 0xaf, 0xb1, 0xdd, 0xa1, 0x6a, 0x2d, 0x65, 0x1c,
	0xa7, 0x99, 0xdb, 0xd0, 0x32, 0xb9, 0xf6, 0x7a, 0xd0, 0xce, 0x37, 0x93, 0x16, 0x34, 0xfa, 0x87,
	0x87, 0xdd, 0x1a, 0x01, 0x68, 0xd2, 0xc1, 0x70, 0xf4, 0x62, 0xd0, 0xad, 0x7b, 0x9f, 0xc0, 0xba,
	0x0e, 0xfb, 0x14, 0xc5, 0x62, 0xc8, 0xd2, 0x8e, 0x09, 0xf9, 0xae, 0x8a, 0x98, 0xe2, 0x85, 0x89,
	0xb8, 0x92, 0x58, 0x8e, 0xca, 0x8d, 0x51, 0xbc, 0xb8, 0x9c, 0x7f, 0x0e, 0xdb, 0x81, 0x1b, 0x1a,
	0x36, 0x7c, 0x61, 0x81, 0x5b, 0xd0, 0x54, 0xba, 0xcc, 0xb8, 0x35, 0x5f, 0xde, 0x23, 0x05, 0x3d,
	0x49, 0x5f, 0xc7, 0xe1, 0xdc, 0xb8, 0xee, 0x81, 0xc3, 0x90, 0x4f, 0xe3, 0x2c, 0x8b, 0xd3, 0xc4,
	0xe2, 0xcb, 0x22, 0xef, 0x0b, 0x55, 0xb0, 0x23, 0x14, 0x7a, 0x9f, 0x72, 0xb0, 0x7c, 0xd7, 0x63,
	0xb5, 0xeb, 0x49, 0x22, 0xf0, 0xe2, 0xdd, 0x65, 0x96, 0x92, 0x0c, 0x85, 0x5b, 0xd7, 0x92, 0x0c,
	0x45, 0x51, 0x78, 0xb3, 0xf5, 0x72, 0xe2, 0xc4, 0x26, 0xfe, 0x35, 0xb4, 0xfb, 0x6c, 0x32, 0x0c,
	0xd8, 0x53, 0x9c, 0x4b, 0x4b, 0xaf, 0x70, 0x6e, 0x4e, 0x46, 0x2e, 0xc9, 0x87, 0xb0, 0xa2, 0x9a,
	0xa0, 0xae, 0x9a, 0x00, 0xfc, 0x03, 0x7a, 0x38, 0x3e, 0x97, 0x12, 0xaa, 0xe4, 0xde, 0x2b, 0x55,
	0x84, 0x61, 0xc0, 0x4c, 0x74, 0xf7, 0xa1, 0x35, 0x53, 0x2b, 0x9d, 0x8f, 0xb3, 0x77, 0xd3, 0xd7,
	0xfa, 0x67, 0x98, 0x09, 0x8c, 0x34, 0x8a, 0x5a, 0x0c, 0xd9, 0x05, 0x87, 0xe3, 0x34, 0x7d, 0x83,
	0xd1, 0x53, 0x9c, 0xeb, 0xde, 0x71, 0xf6, 0xc0, 0xcf, 0x23, 0xa2, 0x65, 0xb5, 0x77, 0x0e, 0xe4,
	0xb2, 0x31, 0x72, 0xa7, 0x08, 0xba, 0xba, 0x57, 0x25, 0xf0, 0x39, 0x34, 0xb5, 0x33, 0x95, 0x82,
	0x89, 0x47, 0xef, 0x1c, 0x31, 0xe4, 0x81, 0x88, 0xd3, 0x84, 0x1a, 0x88, 0xf7, 0x95, 0x6d, 0x96,
	0x61, 0xc0, 0xd4, 0x99, 0xdd, 0x83, 0x16, 0x26, 0x82, 0xc7, 0x79, 0x3a, 0x1d, 0x63, 0x7f, 0x90,
	0x08, 0x3e, 0xa7, 0x56, 0xe9, 0x3d, 0x07, 0xa7, 0x24, 0x5f, 0x12, 0xd2, 0xb6, 0x2d, 0x84, 0x8e,
	0x88, 0xf8, 0xaa, 0x8d, 0x83, 0x68, 0x34, 0xf9, 0x09, 0x43, 0xd5, 0xf1, 0xb6, 0x38, 0x1b, 0xea,
	0x74, 0x0f, 0x78, 0x24, 0xa5, 0x28, 0xbc, 0xef, 0x54, 0x3f, 0x14, 0x71, 0xcb, 0x10, 0x5d, 0x68,
	0x65, 0xb3, 0x30, 0xc4, 0x2c, 0x53, 0xfe, 0xd6, 0xa8, 0xfd, 0x24, 0x77, 0xa0, 0x8d, 0x92, 0x63,
	0x0c, 0x81, 0xd4, 0xb6, 0xd7, 0x69, 0x21, 0xf0, 0x8e, 0x95, 0xad, 0xf1, 0xdb, 0xe4, 0x84, 0xa7,
	0x0c, 0xb9, 0x88, 0x31, 0x23, 0x1f, 0x00, 0x70, 0x0c, 0xa2, 0xf3, 0x5f, 0x78, 0x2c, 0x50, 0xb5,
	0xd8, 0x3a, 0x6d, 0x4b, 0xc9, 0x99, 0x14, 0x90, 0xff, 0xc3, 0x1a, 0xc7, 0xe8, 0x7c, 0xa2, 0x63,
	0x97, 0xca, 0x16, 0xc7, 0x68, 0x5f, 0x46, 0xfa, 0x12, 0x36, 0xfa, 0x6c, 0xb2, 0x9f, 0xce, 0x12,
	0x93, 0xc6, 0xbf, 0xef, 0x25, 0x79, 0xe1, 0x26, 0xb3, 0xf0, 0x15, 0x0a, 0xb7, 0xa1, 0x69, 0x50,
	0x7f, 0x79, 0xbf, 0x29, 0xdb, 0xc5, 0x09, 0x65, 0xe4, 0x11, 0x74, 0x26, 0xd2, 0x55, 0xaa, 0xbf,
	0x4d, 0x6d, 0x6e, 0xf8, 0xd5, 0x10, 0x68, 0x05, 0x44, 0xbe, 0x84, 0x2d, 0xc1, 0x83, 0x24, 0x0b,
	0x42, 0x79, 0x76, 0xe7, 0x11, 0x66, 0x21, 0x8f, 0x99, 0x48, 0xb9, 0x0a, 0xa8, 0x43, 0xff, 0x57,
	0xd2, 0x1e, 0xe6, 0x4a, 0x2f, 0x53, 0xa5, 0xb5, 0x1d, 0x43, 0x1e, 0x82, 0x53, 0xb2, 0x6a, 0x4a,
	0x7c, 0xc9, 0x73, 0x19, 0x43, 0x1e, 0x42, 0x3b, 0xb5, 0x25, 0xbb, 0xae, 0x0b, 0x0b, 0x94, 0xf7,
	0x77, 0x5d, 0xb5, 0xfa, 0x02, 0x82, 0x3c, 0x80, 0x76, 0xa8, 0xa9, 0x3c, 0x65, 0xaa, 0x3c, 0xce,
	0xde, 0xa6, 0xbf, 0xf8, 0x10, 0xd0, 0x02, 0x43, 0x3e, 0x86, 0xd5, 0x0c, 0x45, 0xca, 0x54, 0xb9,
	0x9c, 0xbd, 0xf5, 0x0a, 0x89, 0x53, 0xad, 0x93, 0x20, 0x8e, 0x17, 0x29, 0x73, 0x1b, 0x05, 0x28,
	0xa7, 0x55, 0xaa, 0x75, 0xd2, 0x75, 0xac, 0xc9, 0x24, 0x65, 0xee, 0x4a, 0xe1, 0xba, 0x42, 0x4e,
	0xb4, 0xc0, 0x48, 0xab, 0xd3, 0x80, 0xa5, 0xcc, 0x5d, 0x2d, 0xac, 0xe6, 0x3c, 0x41, 0xb5, 0x8e,
	0x7c, 0x0a, 0x2d, 0x8e, 0x3a, 0xc2, 0x66, 0x01, 0xcb, 0x1b, 0x9e, 0x5a, 0x2d, 0xd9, 0x85, 0x35,
	0xa6, 0x98, 0x33, 0x65, 0x6e, 0x4b, 0x21, 0xbb, 0xfe, 0x02, 0x0b, 0xd3, 0x1c, 0xe1, 0xfd, 0xac,
	0x7a, 0xdb, 0x9c, 0x9e, 0x29, 0xff, 0xbd, 0x45, 0x66, 0xea, 0x94, 0x6b, 0x50, 0x50, 0xd2, 0x7b,
	0xb6, 0xc9, 0x0f, 0x70, 0x53, 0x9e, 0xad, 0x08, 0xb8, 0x18, 0x17, 0x00, 0x79, 0x07, 0x45, 0x3c,
	0xc5, 0x4c, 0x04, 0x53, 0x5d, 0xb1, 0x0e, 0x2d, 0x04, 0xe4, 0x21, 0x00, 0xcb, 0x6f, 0x9f, 0xa9,
	0x91, 0x3a, 0xd5, 0xca, 0xb5, 0xa4, 0x25, 0x90, 0x77, 0xac, 0xfc, 0xf4, 0x27, 0x69, 0xd5, 0xcf,
	0xbb, 0xa3, 0xae, 0x5d, 0x17, 0xf5, 0x10, 0x6e, 0xa9, 0xf6, 0x99, 0x4e, 0xe3, 0xff, 0xc2, 0xdc,
	0x5b, 0xd8, 0xd2, 0x87, 0x20, 0xe2, 0xb0, 0x7a, 0xfa, 0x8f, 0xc1, 0x29, 0x6d, 0x31, 0xd7, 0xe6,
	0x96, 0x7f, 0xc5, 0x91, 0xd1, 0x32, 0xb0, 0x5c, 0xb5, 0xfa, 0x35, 0x55, 0xf3, 0xe6, 0x2a, 0x11,
	0xed, 0xb9, 0xcc, 0x14, 0xef, 0xeb, 0x77, 0x07, 0x5a, 0x96, 0x5c, 0xea, 0x57, 0x93, 0x8b, 0xd5,
	0x7b, 0xbf, 0xd7, 0xe0, 0xf6, 0x55, 0xf6, 0xae, 0x27, 0xe7, 0xeb, 0xda, 0xac, 0xf6, 0xce, 0x13,
	0xae, 0x72, 0x7a, 0x63, 0x91, 0xd3, 0xff, 0xaa, 0xab, 0x87, 0xbf, 0xfa, 0x98, 0x90, 0x5d, 0x68,
	0x19, 0x46, 0x30, 0x9c, 0xa1, 0x5e, 0x9c, 0xea, 0x58, 0x48, 0x2d, 0x84, 0xf4, 0x8a, 0x69, 0xc2,
	0xd9, 0xdb, 0xf0, 0x2b, 0x93, 0x98, 0x9a, 0x2e, 0x24, 0x82, 0xe3, 0x85, 0x61, 0x0b, 0x8b, 0x30,
	0x53, 0x13, 0x95, 0x2a, 0x72, 0x0f, 0x56, 0xa7, 0x6f, 0x24, 0x66, 0xa5, 0xb8, 0xaa, 0xe5, 0xd9,
	0x8a, 0x6a, 0x35, 0xb9, 0x2b, 0x67, 0x19, 0x61, 0x18, 0xc2, 0x46, 0x55, 0x9a, 0x59, 0xe4, 0x7c,
	0xa3, 0xfc, 0x4d, 0x03, 0x4b, 0x10, 0xd6, 0x9f, 0x79, 0xa1, 0xa9, 0x54, 0x91, 0x1d, 0x68, 0xea,
	0xbb, 0x6f, 0xb8, 0x61, 0xd3, 0x5f, 0x1c, 0xb6, 0xa8, 0x01, 0x78, 0xbf, 0x2a, 0x62, 0x2d, 0xb5,
	0xc8, 0x92, 0x3a, 0xed, 0x2e, 0x36, 0xc2, 0x55, 0xcf, 0xb5, 0x85, 0x2c, 0x29, 0xcf, 0x8f, 0x6a,
	0xbc, 0xd0, 0xb7, 0x6d, 0x89, 0xdb, 0x8f, 0xc0, 0x09, 0x15, 0xee, 0x5c, 0xb2, 0x85, 0xe9, 0x09,
	0xd0, 0xa2, 0x71, 0x3c, 0xc5, 0x25, 0x9e, 0xe6, 0xe0, 0x5e, 0x75, 0x1d, 0x94, 0xd3, 0xfb, 0x45,
	0x46, 0xb5, 0xe2, 0x31, 0x5a, 0x40, 0x15, 0x29, 0xf9, 0x60, 0xdc, 0x9a, 0x40, 0xea, 0xb6, 0x08,
	0x45, 0x1e, 0xb4, 0x84, 0xf8, 0xec, 0xcf, 0x1a, 0xb4, 0xf3, 0x97, 0x9d, 0x38, 0xd0, 0x3a, 0x18,
	0x3d, 0x7f, 0x36, 0x1e, 0xd0, 0x6e, 0x83, 0xb4, 0x61, 0x75, 0x44, 0x4f, 0x07, 0xe3, 0xee, 0x8a,
	0x9c, 0xf7, 0x8f, 0xcf, 0xce, 0xe8, 0xe0, 0xa8, 0xbb, 0x2a, 0xc5, 0xc3, 0x17, 0x72, 0xd9, 0x94,
	0xf0, 0x27, 0xcf, 0xc6, 0x83, 0xa3, 0x01, 0xed, 0xb6, 0xc8, 0x1a, 0xac, 0x1c, 0x0d, 0xfb, 0x27,
	0xdd, 0x35, 0x89, 0xe8, 0x9f, 0xc9, 0x65, 0x5b, 0x2e, 0xe9, 0x99, 0xb4, 0x01, 0x6a, 0x49, 0xa5,
	0xd4, 0x21, 0x1b, 0x00, 0xdf, 0xf6, 0xc7, 0xd6, 0x53, 0x47, 0x9a, 0x3f, 0x19, 0x1d, 0x3f, 0x39,
	0xf8, 0xbe, 0xbb, 0xbe, 0xff, 0x18, 0x5c, 0x9c, 0xf9, 0xf6, 0x17, 0x2c, 0x9a, 0xe4, 0x4b, 0x36,
	0xd9, 0x87, 0xbe, 0x59, 0x9f, 0xec, 0xbf, 0xcc, 0xff, 0xd2, 0xc2, 0xd7, 0x31, 0x26, 0xe2, 0x9f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x83, 0x72, 0x9c, 0x94, 0xb6, 0x0d, 0x00, 0x00,
}
